// POSTS
export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILED = "FETCH_POSTS_FAILED";

// POST BY ID
export const FETCH_POST_BY_ID_REQUEST = "FETCH_POST_BY_ID_REQUEST";
export const FETCH_POST_BY_ID_SUCCESS = "FETCH_POST_BY_ID_SUCCESS";
export const FETCH_POST_BY_ID_FAILED = "FETCH_POST_BY_ID_FAILED";

// COMMENTS BY POST ID
export const FETCH_COMMENTS_BY_POST_ID_REQUEST =
  "FETCH_COMMENTS_BY_POST_ID_REQUEST";
export const FETCH_COMMENTS_BY_POST_ID_SUCCESS =
  "FETCH_COMMENTS_BY_POST_ID_SUCCESS";
export const FETCH_COMMENTS_BY_POST_ID_FAILED =
  "FETCH_COMMENTS_BY_POST_ID_FAILED";
